version: "3.8"

services:
  crud:
    build:
      context: .              
      dockerfile: Crud/Dockerfile
    container_name: crud-api
    ports:
      - "8083:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=nice2strangers;User Id=sa;Password=Aug151973!;TrustServerCertificate=True"
    depends_on:
      - sqlserver
    networks:
      - proxy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Aug151973!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always
    networks:
      - proxy

  adminer:
    image: adminer
    restart: always
    ports:
      - "8084:8080"
    networks:
      - proxy

volumes:
  sql_data:

networks:
  proxy:
    external: true 




# version: "3.8"

# services:
#   crud:
#     build:
#       context: .
#       dockerfile: Crud/Dockerfile
#     ports:
#       - "8083:8080"
#     environment:
#       ASPNETCORE_ENVIRONMENT: "Production"
#       ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=nice2strangers;User Id=sa;Password=Aug151973!;TrustServerCertificate=True"
#     depends_on:
#       - sqlserver

#   sqlserver:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: sqlserver
#     environment:
#       SA_PASSWORD: "Aug151973!"
#       ACCEPT_EULA: "Y"
#       MSSQL_PID: "Express"
#     ports:
#       - "1433:1433"
#     volumes:
#       - sql_data:/var/opt/mssql
#     restart: always

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8084:8080

# volumes:
#   sql_data:

